#!/usr/bin/env bash
# Script that displays information about subdomains

# Function to display subdomain information
display_info() {
    local domain=$1
    local subdomain=$2
    # shellcheck disable=SC2086
    local result=$(dig ${subdomain}.${domain} | grep -A1 'ANSWER SECTION:' | tail -n 1)
    local record_type=$(echo "$result" | awk '{print $4}')
    local destination=$(echo "$result" | awk '{print $5}')
    
    if [ -n "$destination" ]; then
        echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
    fi
}

# Main logic
if [ $# -eq 1 ]; then
    # Display info for default subdomains
    display_info "$1" "www"
    display_info "$1" "lb-01"
    display_info "$1" "web-01"
    display_info "$1" "web-02"
elif [ $# -eq 2 ]; then
    # Display info for specific subdomain
    display_info "$1" "$2"
fi
